### PR TITLE
Request to add H6602 (AI TV Sync box)

### PR DESCRIPTION
**Pull request by perkalkyl**
Dear sir

This is my very first pull request for someone else's code, as I normally only use Github for my private development (ie no pull requests) so I am not sure if I do this right.
If there is anything else I should do, then please don't hesitate to contact me.

BR
Per

### CODE REVIEW

**Comment by kaohlive** [comment]
Thanks for contributing. That is highly appreciated. I am working these days on a major rework of the app that is getting rid of the individual device drivers. I will finish that first and check out your svg etc and move it manually in.
In the new version, all that is needed to onboard new govee liggts is the svg.
So i am converting all product images into svg as we speak.

**Comment by perkalkyl** [comment]
Sounds amazing!If I can assist you, I'll be happy to.I'm really more of a C# developer, but I've done my fair share of Javascript and html. :-)Let's keep in touchBrPerSkickat från min Galaxy
-------- Originalmeddelande --------Från: kaohlive ***@***.***> Datum: 2023-08-07  12:22  (GMT+01:00) Till: "kaohlive/com.govee.developer" ***@***.***> Kopia: Per Malmstedt ***@***.***>, Author ***@***.***> Ämne: Re: [kaohlive/com.govee.developer] Request to add H6602 (AI TV Sync box) (PR #3) 
Thanks for contributing. That is highly appreciated. I am working these days on a major rework of the app that is getting rid of the individual device drivers. I will finish that first and check out your svg etc and move it manually in.
In the new version, all that is needed to onboard new govee liggts is the svg.
So i am converting all product images into svg as we speak.

**Comment by kaohlive** [comment]
The new version is ready in github and on test status in the homey store. Please try that version

**Comment by kaohlive** [comment]
Next will be an attempt to support the appliances, different API endpoint and less capabilities, so should be easy.
But I can use some help with the local api support, I havent investigated what the homey device needs to understand to make the local api work. I assue it requires a local discovery method (so other list_devices code) and figure out what the best strategy is to support it, a new device driver or can we make it a setting on each device.

**Pull request closed without merging**
